package grub

import (
	"fmt"
	"path"
	"sort"
	"strings"

	filesystem "github.com/go-filesystems/interface"
)

// Kernel is a discovered (kernel, initrd) pair on a mounted filesystem.
type Kernel struct {
	// Version is the release string parsed from the vmlinuz name, e.g.
	// "6.1.0-18-amd64" from "vmlinuz-6.1.0-18-amd64". Empty for an
	// un-versioned "vmlinuz".
	Version string
	// KernelPath is the absolute path of the kernel image on the FS.
	KernelPath string
	// InitrdPath is the absolute path of the matching initrd/initramfs, or
	// empty when none was found.
	InitrdPath string
}

// kernelScanDirs lists where kernels conventionally live, relative to the
// mounted filesystem root. /boot is first (a /boot partition or the /boot
// subtree of root); the ESP root and /EFI come after for ESP-resident kernels.
var kernelScanDirs = []string{"/boot", "/", "/EFI"}

// MkConfigOptions tunes generated grub.cfg output.
type MkConfigOptions struct {
	// Default is the index of the default menu entry. Defaults to 0.
	Default int
	// Timeout is the menu timeout in seconds. Defaults to 5.
	Timeout int
	// Cmdline is appended to every linux line (after the root= argument the
	// caller bakes in). Typical value: "ro console=tty0 console=hvc0".
	Cmdline string
	// Distributor labels the menu entries, e.g. "Debian GNU/Linux".
	Distributor string
}

func (o MkConfigOptions) withDefaults() MkConfigOptions {
	if o.Timeout == 0 {
		o.Timeout = 5
	}
	if o.Distributor == "" {
		o.Distributor = "Linux"
	}
	if o.Cmdline == "" {
		o.Cmdline = "ro console=tty0 console=hvc0"
	}
	return o
}

// isKernelName reports whether name looks like a kernel image
// (vmlinuz*, vmlinux*, or kernel*).
func isKernelName(name string) bool {
	lower := strings.ToLower(name)
	return strings.HasPrefix(lower, "vmlinuz") ||
		strings.HasPrefix(lower, "vmlinux") ||
		strings.HasPrefix(lower, "kernel")
}

// kernelVersion extracts the release suffix from a kernel filename, i.e. the
// text after the first '-'. "vmlinuz-6.1.0" -> "6.1.0"; "vmlinuz" -> "".
func kernelVersion(name string) string {
	if i := strings.IndexByte(name, '-'); i >= 0 {
		return name[i+1:]
	}
	return ""
}

// initrdCandidates returns the conventional initrd filenames that pair with a
// kernel of the given version, in priority order.
func initrdCandidates(version string) []string {
	if version == "" {
		return []string{
			"initrd.img", "initramfs.img", "initrd", "initramfs",
		}
	}
	return []string{
		"initrd.img-" + version,
		"initramfs-" + version + ".img",
		"initrd-" + version,
		"initramfs-" + version,
		"initrd.img." + version,
	}
}

// DiscoverKernels scans the conventional directories of a mounted filesystem
// for kernel images and their matching initrds. Results are sorted by version
// descending (newest first) so the default entry is the newest kernel.
func DiscoverKernels(fs filesystem.Filesystem) ([]Kernel, error) {
	seen := map[string]bool{}
	var kernels []Kernel
	for _, dir := range kernelScanDirs {
		entries, err := fs.ListDir(dir)
		if err != nil {
			continue // directory absent on this FS; skip
		}
		// Build a name set for fast initrd lookup in the same dir.
		names := map[string]bool{}
		for _, e := range entries {
			names[e.Name()] = true
		}
		for _, e := range entries {
			name := e.Name()
			if name == "." || name == ".." || !isKernelName(name) {
				continue
			}
			kp := path.Join(dir, name)
			if seen[kp] {
				continue
			}
			seen[kp] = true
			ver := kernelVersion(name)
			k := Kernel{Version: ver, KernelPath: kp}
			for _, cand := range initrdCandidates(ver) {
				if names[cand] {
					k.InitrdPath = path.Join(dir, cand)
					break
				}
			}
			kernels = append(kernels, k)
		}
	}
	sort.SliceStable(kernels, func(i, j int) bool {
		// Newest version first; lexical compare on the reversed version is a
		// reasonable, deterministic proxy across distro naming schemes.
		return kernels[i].Version > kernels[j].Version
	})
	return kernels, nil
}

// GenerateConfig renders a grub.cfg from a list of kernels. The output is a
// complete, valid GRUB configuration: a header (set default/timeout, load the
// needed modules), one menuentry per kernel with a linux + initrd line, and
// proper quoting. It does not touch the filesystem.
func GenerateConfig(kernels []Kernel, opts MkConfigOptions) string {
	opts = opts.withDefaults()
	var b strings.Builder

	b.WriteString("# grub.cfg generated by github.com/go-bootloaders/grub\n")
	b.WriteString("# Do not edit by hand; regenerate with grub.MkConfig.\n\n")
	fmt.Fprintf(&b, "set default=%d\n", opts.Default)
	fmt.Fprintf(&b, "set timeout=%d\n", opts.Timeout)
	b.WriteString("\n")
	// Module loads needed for ext-rooted, gzio-compressed kernels on a GPT
	// disk. insmod is idempotent in GRUB.
	for _, mod := range []string{"part_gpt", "fat", "ext2", "gzio", "linux", "echo"} {
		fmt.Fprintf(&b, "insmod %s\n", mod)
	}
	b.WriteString("\n")

	for _, k := range kernels {
		label := opts.Distributor
		if k.Version != "" {
			label = fmt.Sprintf("%s (%s)", opts.Distributor, k.Version)
		}
		fmt.Fprintf(&b, "menuentry %s {\n", quoteMenuTitle(label))
		fmt.Fprintf(&b, "\tlinux %s %s\n", k.KernelPath, opts.Cmdline)
		if k.InitrdPath != "" {
			fmt.Fprintf(&b, "\tinitrd %s\n", k.InitrdPath)
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

// quoteMenuTitle wraps a menu title in single quotes (GRUB's literal quoting),
// escaping any embedded single quotes the GRUB way ('\”).
func quoteMenuTitle(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// MkConfig discovers the kernels on the mounted ESP, generates a grub.cfg, and
// writes it to the conventional ESP location (/grub/grub.cfg, or the path of an
// existing grub.cfg if one is already present). It returns the path written and
// the number of menu entries emitted.
//
// This replaces the former no-op stub: it produces a real, valid configuration
// from on-disk kernels rather than returning nil.
func (im *Image) MkConfig(opts MkConfigOptions) (cfgPath string, entries int, err error) {
	kernels, err := DiscoverKernels(im.esp)
	if err != nil {
		return "", 0, err
	}
	if len(kernels) == 0 {
		return "", 0, fmt.Errorf("grub: MkConfig: no kernels found on ESP")
	}
	content := GenerateConfig(kernels, opts)

	// Prefer an existing grub.cfg location; otherwise default to /grub/grub.cfg.
	target, err := LocateGrubCfg(im.esp)
	if err != nil {
		target = "/grub/grub.cfg"
		if mkErr := mkDirAll(im.esp, path.Dir(target)); mkErr != nil {
			return "", 0, fmt.Errorf("grub: MkConfig: create dir: %w", mkErr)
		}
	}
	if err := im.WriteGrubCfg(target, content); err != nil {
		return "", 0, err
	}
	return target, len(kernels), nil
}

// mkDirAll creates dir and all missing parents on a mounted filesystem,
// tolerating already-existing components.
func mkDirAll(fs filesystem.Filesystem, dir string) error {
	dir = path.Clean(dir)
	if dir == "/" || dir == "." || dir == "" {
		return nil
	}
	parts := strings.Split(strings.TrimPrefix(dir, "/"), "/")
	cur := ""
	for _, p := range parts {
		cur += "/" + p
		if _, err := fs.Stat(cur); err == nil {
			continue
		}
		if err := fs.MkDir(cur, 0o755); err != nil {
			// A racing/already-present dir is fine; re-stat to confirm.
			if _, serr := fs.Stat(cur); serr != nil {
				return err
			}
		}
	}
	return nil
}
